[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sparkenv"
version = "0.0.1"
dependencies = [
    'click',
    'beautifulsoup4',
    'requests',
    'importlib-metadata; python_version<"3.11"',
]

[project.scripts]
sparkenv = "sparkenv:main"